#!/bin/zsh

login_user=$(/usr/bin/stat -f%Su /dev/console)
executable="/Library/Input Methods/Prompt.app/Contents/MacOS/Prompt"

# Terminate running instances
osascript -e 'tell application id "hk.eduhk.inputmethod.Prompt" to quit'
/usr/bin/sudo -u "${login_user}" osascript -e 'tell application id "hk.eduhk.inputmethod.Prompt" to quit'

# Install
/usr/bin/sudo -u "${login_user}" "${executable}" install

# Terminate running instances
osascript -e 'tell application id "hk.eduhk.inputmethod.Prompt" to quit'
/usr/bin/sudo -u "${login_user}" osascript -e 'tell application id "hk.eduhk.inputmethod.Prompt" to quit'

exit 0
